"""empty message

Revision ID: 3893f138765f
Revises: 1f90e8d89c01
Create Date: 2022-08-17 15:44:27.472874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3893f138765f'
down_revision = '1f90e8d89c01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookmark', sa.Column('state_name', sa.String(length=256), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookmark', 'state_name')
    # ### end Alembic commands ###
