"""empty message

Revision ID: 8f95d5dceaee
Revises: abf57174297e
Create Date: 2022-08-08 17:48:14.521433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f95d5dceaee'
down_revision = 'abf57174297e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bookmark_city_name_fkey', 'bookmark', type_='foreignkey')
    op.drop_column('bookmark', 'city_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookmark', sa.Column('city_name', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('bookmark_city_name_fkey', 'bookmark', 'city', ['city_name'], ['id'])
    # ### end Alembic commands ###
