"""empty message

Revision ID: abf57174297e
Revises: 5cfefe39498a
Create Date: 2022-08-08 17:40:20.885864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abf57174297e'
down_revision = '5cfefe39498a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookmark', sa.Column('city_name', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bookmark', 'city', ['city_name'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookmark', type_='foreignkey')
    op.drop_column('bookmark', 'city_name')
    # ### end Alembic commands ###
