"""empty message

Revision ID: df71643e516e
Revises: 3bb645893267
Create Date: 2022-08-05 23:19:47.195925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df71643e516e'
down_revision = '3bb645893267'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('city', sa.Column('code', sa.String(length=256), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('city', 'code')
    # ### end Alembic commands ###
