"""empty message

Revision ID: ecdad50865dc
Revises: 8f95d5dceaee
Create Date: 2022-08-09 18:09:20.266039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecdad50865dc'
down_revision = '8f95d5dceaee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('city', sa.Column('code', sa.String(length=256), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('city', 'code')
    # ### end Alembic commands ###
